export interface PartnerPrice {
  name: string;
  url: string;
  minPrice: number;
  maxPrice: number;
  currency: string;
  available: boolean;
}

export interface Event {
  slug: string;
  title: string;
  subtitle: string;
  date: string;
  dateDisplay: string;
  venue: string;
  city: string;
  country: string;
  category: string;
  categoryColor: string;
  image: string;
  description: string;
  minPrice: number;
  maxPrice: number;
  partners: PartnerPrice[];
  featured: boolean;
}

export const PARTNERS = [
  { name: "Eventim.hu", url: "https://www.eventim.hu", logo: "eventim" },
  { name: "AXS.com", url: "https://www.axs.com", logo: "axs" },
  { name: "StubHub", url: "https://www.stubhub.com", logo: "stubhub" },
  { name: "Viagogo", url: "https://www.viagogo.com", logo: "viagogo" },
  { name: "Ticketmaster", url: "https://www.ticketmaster.com", logo: "ticketmaster" },
  { name: "Jegymester.hu", url: "https://www.jegymester.hu", logo: "jegymester" },

];

export const EVENTS: Event[] = [
  {
    slug: "ucl-donjo-2026",
    title: "UEFA Bajnokok Ligája Döntő 2026",
    subtitle: "A legrangosabb európai klubfutball döntő",
    date: "2026-05-30",
    dateDisplay: "2026. május 30.",
    venue: "Allianz Arena",
    city: "München",
    country: "Németország",
    category: "Labdarúgás",
    categoryColor: "primary",
    image: "/events/ucl-final.jpg",
    description: "A 2026-os UEFA Bajnokok Ligája döntője Münchenben kerül megrendezésre az Allianz Arénában. Európa legjobb klubjai mérnek össze tudást ebben az ünnepi, legendás mérkőzésen.",
    minPrice: 45000,
    maxPrice: 285000,
    featured: true,
    partners: [
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 52000, maxPrice: 285000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 48000, maxPrice: 260000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 45000, maxPrice: 240000, currency: "HUF", available: true },
      { name: "AXS.com", url: "https://www.axs.com", minPrice: 55000, maxPrice: 275000, currency: "HUF", available: true },
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 50000, maxPrice: 255000, currency: "HUF", available: false },
    ],
  },
  {
    slug: "f1-magyar-nagydij-2026",
    title: "Formula 1 Magyar Nagydíj 2026",
    subtitle: "Hungaroring – A legkanyargósabb F1-es pálya",
    date: "2026-08-02",
    dateDisplay: "2026. augusztus 2.",
    venue: "Hungaroring",
    city: "Budapest",
    country: "Magyarország",
    category: "Motorsport",
    categoryColor: "accent",
    image: "/events/f1-hungary.jpg",
    description: "A Magyar Nagydíj a Hungaroringen évről évre az F1-es szezon egyik legizgalmasabb futama. Budapest közelében, a kanyargós pályán a legjobb versenyzők mérik össze tudásukat.",
    minPrice: 35000,
    maxPrice: 195000,
    featured: true,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 35000, maxPrice: 195000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 42000, maxPrice: 185000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 38000, maxPrice: 180000, currency: "HUF", available: true },
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 36000, maxPrice: 165000, currency: "HUF", available: true },
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 37000, maxPrice: 170000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "magyarorszag-hollandia-2026",
    title: "Magyarország vs Hollandia – VB-selejtező",
    subtitle: "FIFA Világbajnokság Selejtező – Puskás Aréna",
    date: "2026-09-04",
    dateDisplay: "2026. szeptember 4.",
    venue: "Puskás Aréna",
    city: "Budapest",
    country: "Magyarország",
    category: "Labdarúgás",
    categoryColor: "primary",
    image: "/events/hungary-football.jpg",
    description: "A magyar válogatott FIFA Világbajnoki selejtezőn fogadja Hollandiát a Puskás Arénában. A mérkőzés sorsdöntő lehet a továbbjutás szempontjából.",
    minPrice: 12000,
    maxPrice: 48000,
    featured: true,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 12000, maxPrice: 38000, currency: "HUF", available: true },
    
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 14000, maxPrice: 45000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 18000, maxPrice: 48000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 16000, maxPrice: 44000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "atp-budapest-open-2026",
    title: "ATP Budapest Open 2026",
    subtitle: "Salak borítású tenisztorna – Római Sportclub",
    date: "2026-04-20",
    dateDisplay: "2026. április 20.",
    venue: "Római Sportclub",
    city: "Budapest",
    country: "Magyarország",
    category: "Tenisz",
    categoryColor: "primary",
    image: "/events/tennis-clay.jpg",
    description: "Az ATP Budapest Open a világ legjobb teniszezőit vonzza a Dunakanyar melletti csodás helyszínre. Salak pályán, legendás légkörben zajlik a verseny.",
    minPrice: 8000,
    maxPrice: 55000,
    featured: false,
    partners: [
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 8000, maxPrice: 45000, currency: "HUF", available: true },
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 8500, maxPrice: 42000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 10000, maxPrice: 55000, currency: "HUF", available: true },
     
    ],
  },
  {
    slug: "magyar-kupa-donjo-2026",
    title: "Magyar Kupa Döntő 2026",
    subtitle: "A hazai futball legnagyobb trófeájának döntője",
    date: "2026-05-16",
    dateDisplay: "2026. május 16.",
    venue: "Puskás Aréna",
    city: "Budapest",
    country: "Magyarország",
    category: "Labdarúgás",
    categoryColor: "primary",
    image: "/events/cup-final.jpg",
    description: "A Magyar Kupa döntője az évad legnagyobb hazai futballesemény. A Puskás Arénában ünnepi légkörben dől el, melyik csapat emeli magasba a kupát.",
    minPrice: 6000,
    maxPrice: 25000,
    featured: false,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 6000, maxPrice: 18000, currency: "HUF", available: true },
      
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 7000, maxPrice: 22000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 8000, maxPrice: 25000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "motogp-ausztria-2026",
    title: "MotoGP Ausztriai Nagydíj 2026",
    subtitle: "Red Bull Ring – Robogjon a motor!",
    date: "2026-08-09",
    dateDisplay: "2026. augusztus 9.",
    venue: "Red Bull Ring",
    city: "Spielberg",
    country: "Ausztria",
    category: "Motorsport",
    categoryColor: "accent",
    image: "/events/motogp.jpg",
    description: "A MotoGP Ausztriai Nagydíja a Red Bull Ringen kerül megrendezésre. A világ legjobb motorosai versenyeznek a gyönyörű stájer tájak között.",
    minPrice: 42000,
    maxPrice: 180000,
    featured: false,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 42000, maxPrice: 165000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 48000, maxPrice: 180000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 45000, maxPrice: 170000, currency: "HUF", available: true },
      { name: "AXS.com", url: "https://www.axs.com", minPrice: 50000, maxPrice: 175000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "wimbledon-donjo-2026",
    title: "Wimbledon Döntő 2026",
    subtitle: "A legrangosabb Grand Slam torna fináléja",
    date: "2026-07-13",
    dateDisplay: "2026. július 13.",
    venue: "All England Lawn Tennis Club",
    city: "London",
    country: "Egyesült Királyság",
    category: "Tenisz",
    categoryColor: "primary",
    image: "/events/wimbledon.jpg",
    description: "A Wimbledon döntő a tenisz legpatinásabb eseménye, ahol a fűpályán a világ legjobb teniszezői csapnak össze. Egyedülálló brit elegancia és sportdráma.",
    minPrice: 85000,
    maxPrice: 420000,
    featured: true,
    partners: [
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 95000, maxPrice: 420000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 88000, maxPrice: 395000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 85000, maxPrice: 380000, currency: "HUF", available: true },
      { name: "AXS.com", url: "https://www.axs.com", minPrice: 92000, maxPrice: 410000, currency: "HUF", available: false },
    ],
  },
  {
    slug: "tour-de-france-2026",
    title: "Tour de France – Párizsi Befejezés 2026",
    subtitle: "A világ leghíresebb kerékpáros versenyének zárószakasza",
    date: "2026-07-26",
    dateDisplay: "2026. július 26.",
    venue: "Champs-Élysées",
    city: "Párizs",
    country: "Franciaország",
    category: "Kerékpár",
    categoryColor: "primary",
    image: "/events/tour-de-france.jpg",
    description: "A Tour de France utolsó szakasza a Champs-Élysées-n végzetes döntőt hoz. Millió néző tapsol a pelotán legkiválóbbjainak a Szajna partján.",
    minPrice: 15000,
    maxPrice: 75000,
    featured: false,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 15000, maxPrice: 68000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 18000, maxPrice: 75000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 16000, maxPrice: 72000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "jegkorong-vb-donjo-2026",
    title: "Jégkorong Világbajnokság Döntő 2026",
    subtitle: "IIHF VB döntő – O2 Arena, Prága",
    date: "2026-05-24",
    dateDisplay: "2026. május 24.",
    venue: "O2 Arena",
    city: "Prága",
    country: "Csehország",
    category: "Jégkorong",
    categoryColor: "primary",
    image: "/events/ice-hockey.jpg",
    description: "A Jégkorong Világbajnokság döntője Prágában zajlik. A legjobb nemzeiti csapatok küzdenek az aranyéremért a cseh főváros ikonikus arénájában.",
    minPrice: 25000,
    maxPrice: 120000,
    featured: false,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 25000, maxPrice: 110000, currency: "HUF", available: true },
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 28000, maxPrice: 120000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 30000, maxPrice: 115000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 27000, maxPrice: 112000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "roland-garros-donjo-2026",
    title: "Roland Garros Döntő 2026",
    subtitle: "Francia Open – A salakpályás tenisz csúcsa",
    date: "2026-06-07",
    dateDisplay: "2026. június 7.",
    venue: "Stade Roland Garros",
    city: "Párizs",
    country: "Franciaország",
    category: "Tenisz",
    categoryColor: "primary",
    image: "/events/roland-garros.jpg",
    description: "A Roland Garros döntő a tenisz egyik legprestizsebb eseménye. A párizsi salakpályán folyik az agyagkirályok csatája a Grand Slam-trófeáért.",
    minPrice: 70000,
    maxPrice: 350000,
    featured: true,
    partners: [
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 78000, maxPrice: 350000, currency: "HUF", available: true },
      { name: "Viagogo", url: "https://www.viagogo.com", minPrice: 72000, maxPrice: 325000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 70000, maxPrice: 310000, currency: "HUF", available: true },
      { name: "AXS.com", url: "https://www.axs.com", minPrice: 80000, maxPrice: 340000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "boksz-vb-budapest-2026",
    title: "Boksz VB: Super Heavyweight 2026",
    subtitle: "Világbajnoki bokszgála – BOK Hall, Budapest",
    date: "2026-09-19",
    dateDisplay: "2026. szeptember 19.",
    venue: "BOK Hall",
    city: "Budapest",
    country: "Magyarország",
    category: "Boksz",
    categoryColor: "accent",
    image: "/events/boxing.jpg",
    description: "Budapest adott otthont a Super Heavyweight bokszvilágbajnokságnak. A BOK Hallban két világ legjobb nehézsúlyú bokszolója csap össze a trófeáért.",
    minPrice: 18000,
    maxPrice: 95000,
    featured: false,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 18000, maxPrice: 75000, currency: "HUF", available: true },
      
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 22000, maxPrice: 88000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 25000, maxPrice: 95000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "europai-atletika-bajnoksag-2026",
    title: "Európai Atlétikai Bajnokság 2026",
    subtitle: "A kontinens legjobb atlétái – Amszterdam Arena",
    date: "2026-08-14",
    dateDisplay: "2026. augusztus 14.",
    venue: "Amsterdam ArenA",
    city: "Amszterdam",
    country: "Hollandia",
    category: "Atlétika",
    categoryColor: "primary",
    image: "/events/athletics.jpg",
    description: "Az Európai Atlétikai Bajnokság Amszterdamban kerül megrendezésre. Futó-, ugró- és dobószámokban a kontinens legjobb sportolói versenyeznek az aranyéremért.",
    minPrice: 22000,
    maxPrice: 88000,
    featured: false,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 22000, maxPrice: 82000, currency: "HUF", available: true },
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 24000, maxPrice: 88000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 28000, maxPrice: 85000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "budapest-maraton-2026",
    title: "Budapest Maraton 2026",
    subtitle: "A Duna-parti futás ünnepe – Hősök tere",
    date: "2026-10-11",
    dateDisplay: "2026. október 11.",
    venue: "Hősök tere",
    city: "Budapest",
    country: "Magyarország",
    category: "Futás",
    categoryColor: "primary",
    image: "/events/marathon.jpg",
    description: "A Budapest Maraton évente hívja az őszi Dunakanyarba a futóvilág élvonalát. A Hősök teréről induló és a Lánchídon átvezető útvonal egyedülálló látvány.",
    minPrice: 8500,
    maxPrice: 35000,
    featured: false,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 8500, maxPrice: 28000, currency: "HUF", available: true },
      
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 10000, maxPrice: 35000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "ferencvaros-paok-uefa-2026",
    title: "Ferencváros vs PAOK – UEFA Konferencia Liga",
    subtitle: "Puskás Aréna – Európai kupameccs",
    date: "2026-08-20",
    dateDisplay: "2026. augusztus 20.",
    venue: "Puskás Aréna",
    city: "Budapest",
    country: "Magyarország",
    category: "Labdarúgás",
    categoryColor: "primary",
    image: "/events/fradi-uefa.jpg",
    description: "A Ferencváros UEFA Konferencia Liga csoportmeccsén fogadja a görög PAOK-ot a Puskás Arénában. A Fradi-szurkolók hatalmas hangulatot varázsolnak.",
    minPrice: 10000,
    maxPrice: 45000,
    featured: false,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 10000, maxPrice: 35000, currency: "HUF", available: true },
     
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 12000, maxPrice: 42000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 13000, maxPrice: 45000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "davis-cup-donjo-2026",
    title: "Davis Kupa Döntő 2026",
    subtitle: "A tenisz csapatvilágbajnoksága – Budapest",
    date: "2026-11-22",
    dateDisplay: "2026. november 22.",
    venue: "Papp László Sportaréna",
    city: "Budapest",
    country: "Magyarország",
    category: "Tenisz",
    categoryColor: "primary",
    image: "/events/davis-cup.jpg",
    description: "A Davis Kupa döntőjét Budapesten rendezik meg a Papp László Sportarénában. A tenisz csapatvilágbajnokságának legizgalmasabb mérkőzései várják a közönséget.",
    minPrice: 15000,
    maxPrice: 65000,
    featured: false,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 15000, maxPrice: 60000, currency: "HUF", available: true },
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 16000, maxPrice: 62000, currency: "HUF", available: true },
    
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 16500, maxPrice: 63000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "giro-ditalia-budapest-2026",
    title: "Giro d'Italia 2026 – Budapesti Rajt",
    subtitle: "A nagy körverseny első szakasza Budapestről indul",
    date: "2026-05-09",
    dateDisplay: "2026. május 9.",
    venue: "Hősök tere",
    city: "Budapest",
    country: "Magyarország",
    category: "Kerékpár",
    categoryColor: "primary",
    image: "/events/giro-italia.jpg",
    description: "A Giro d'Italia 2026-os kiadása Budapestről rajtol. A Hősök teréről induló első szakasz Magyarország fővárosát teszi a kerékpársport világának középpontjává.",
    minPrice: 5000,
    maxPrice: 28000,
    featured: false,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 5000, maxPrice: 22000, currency: "HUF", available: true },
    
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 6000, maxPrice: 28000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "magyarorszag-szerbia-eb-selektejo-2026",
    title: "Magyarország vs Szerbia – EB-selejtező",
    subtitle: "UEFA Európa-bajnokság selejtező – Puskás Aréna",
    date: "2026-10-09",
    dateDisplay: "2026. október 9.",
    venue: "Puskás Aréna",
    city: "Budapest",
    country: "Magyarország",
    category: "Labdarúgás",
    categoryColor: "primary",
    image: "/events/euro-qualifier.jpg",
    description: "A magyar válogatott UEFA Európa-bajnoki selejtezőn fogadja Szerbiát. A meccsen mindkét csapat a továbbjutásért küzd, ami garantálja a felejthetetlen hangulatot.",
    minPrice: 8000,
    maxPrice: 32000,
    featured: false,
    partners: [
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 8000, maxPrice: 26000, currency: "HUF", available: true },
      
      { name: "Eventim.hu", url: "https://www.eventim.hu", minPrice: 9000, maxPrice: 30000, currency: "HUF", available: true },
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 10000, maxPrice: 32000, currency: "HUF", available: true },
    ],
  },
  {
    slug: "mma-world-championship-budapest-2026",
    title: "MMA Világbajnokság Budapest 2026",
    subtitle: "A vegyes harcművészetek világ legjobbjainak gálája",
    date: "2026-12-05",
    dateDisplay: "2026. december 5.",
    venue: "BOK Hall",
    city: "Budapest",
    country: "Magyarország",
    category: "MMA",
    categoryColor: "accent",
    image: "/events/mma.jpg",
    description: "Az MMA Világbajnokság Budapesten kerül megrendezésre a BOK Hallban. A vegyes harcművészetek legjobb sportolói küzdenek meg az öt különböző súlycsoport aranyérmeiért.",
    minPrice: 20000,
    maxPrice: 110000,
    featured: false,
    partners: [
      { name: "Ticketmaster", url: "https://www.ticketmaster.com", minPrice: 20000, maxPrice: 100000, currency: "HUF", available: true },
      { name: "AXS.com", url: "https://www.axs.com", minPrice: 22000, maxPrice: 110000, currency: "HUF", available: true },
      { name: "StubHub", url: "https://www.stubhub.com", minPrice: 24000, maxPrice: 105000, currency: "HUF", available: true },
      { name: "Jegymester.hu", url: "https://www.jegymester.hu", minPrice: 21000, maxPrice: 95000, currency: "HUF", available: true },
    ],
  },
];

export function getEventBySlug(slug: string): Event | undefined {
  return EVENTS.find((e) => e.slug === slug);
}

export function getFeaturedEvents(): Event[] {
  return EVENTS.filter((e) => e.featured);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("hu-HU").format(price) + " Ft";
}
